(function(){
'use strict';
var ORDER_KEY='daham_order_v1',SCHED_KEY='daham_schedule_v1',EST_KEY='daham_detail_v2',CONTACT_KEY='daham_contacts_v1';
var records=[],sites=[],estimates=[],contacts=[],mode='general',editingRecord=null,brand='KCC',windowMode='완성창';
var BRANDS=['KCC','LX','영림','대우하이원'],WINDOW_TYPES=['외창이중창','외창단창','내창이중창','내창단창','분합창','터닝도어','픽스창','기타'];
function parse(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d));}catch(e){return d;}}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');}
function val(id){var e=document.getElementById(id);return e?e.value.trim():'';}function set(id,v){var e=document.getElementById(id);if(e)e.value=v||'';}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7);}function user(){try{return DAHAM_AUTH.currentUser()||{};}catch(e){return {};}}
function toast(s){var e=document.getElementById('o-toast');e.textContent=s;e.classList.add('show');setTimeout(function(){e.classList.remove('show');},1800);}
function load(){records=parse(ORDER_KEY,[]);estimates=parse(EST_KEY,[]);sites=DAHAM_ACTIVE_SITES.filterSchedules(parse(SCHED_KEY,[]),estimates);contacts=parse(CONTACT_KEY,[]);}
function fields(){return '<div class="field wide"><label>연결 현장 *</label><select id="o-site"></select></div><div class="field"><label>연결 공종</label><select id="o-trade"></select></div><div class="field"><label>거래처</label><select id="o-vendor"></select></div><div class="field full"><label>현장 주소</label><input id="o-address"></div><div class="field"><label>상세 주소</label><input id="o-detail-address"></div><div class="field"><label>희망 납기일</label><input id="o-delivery" type="date"></div><div class="field"><label>공동현관 비밀번호</label><input id="o-common" type="password"></div><div class="field"><label>세대 현관 비밀번호</label><input id="o-door" type="password"></div><div class="field"><label>배송 위치</label><input id="o-location" placeholder="예: 현관 앞"></div><div class="field"><label>현장 담당자</label><input id="o-manager"></div><div class="field"><label>담당자 전화번호</label><input id="o-manager-phone" inputmode="tel"></div><div class="field"><label>보조 연락처</label><input id="o-sub-phone" inputmode="tel" placeholder="선택 입력"></div><div class="field wide"><label>배송 요청사항</label><input id="o-delivery-request"></div><div class="field wide"><label>배송기사 전달사항</label><input id="o-driver-note"></div>';}
function shell(){document.body.className='order-v2';document.body.innerHTML='<div class="order-shell"><aside class="order-side"><div class="order-logo">DAHAM<small>INTERIOR RENOVATION</small></div><nav class="order-nav"><a href="index.html">⌂ <span>대시보드</span></a><a href="estimate.html">▤ <span>견적 관리</span></a><a href="order.html" class="active">▣ <span>발주 작성</span></a><a href="contacts.html">♙ <span>업체 관리</span></a><a href="schedule.html">□ <span>일정 관리</span></a><a href="employees.html">⚙ <span>설정</span></a></nav><div class="order-user"><strong id="o-user">DAHAM</strong><span>사용자</span></div></aside><main class="order-main"><header class="order-head"><div><small>PURCHASE ORDER</small><h1>발주 작성</h1></div><div class="head-actions"><button class="o-btn" id="open-list">발주 목록</button><button class="o-btn" id="draft-save">임시저장</button><button class="o-btn primary" id="save-order">저장</button></div></header><nav class="order-mode-tabs"><button data-mode="general" class="active">일반 발주</button><button data-mode="quote">견적 발주</button></nav><div class="order-work"><section><div class="order-card basic"><div class="card-title" id="writer-title">일반 발주 작성</div><div class="form-grid">'+fields()+'</div></div><div id="general-editor" class="order-card editor-card"><div class="card-title">발주 내용</div><textarea id="order-content" class="free-editor" placeholder="거래처에 보낼 발주 내용을 자유롭게 작성하세요."></textarea></div><div id="quote-editor" class="order-card editor-card" hidden><div class="card-title">창호 견적 발주 빠른 삽입</div><div class="quick-row"><b>창호 브랜드</b><div id="brand-chips"></div></div><div class="quick-row"><b>제작 방식</b><div id="mode-chips"></div><small>완성창은 KCC·LX만 선택할 수 있습니다.</small></div><div class="quick-row"><b>창호 종류</b><div id="window-chips"></div></div><span id="quote-selection" class="selection-badge"></span><textarea id="quote-content" class="free-editor quote" placeholder="창호 견적 요청 내용을 자유롭게 작성하세요."></textarea></div></section><aside class="right-stack"><section class="order-card side-card share-card"><div class="share-head"><h3>공유</h3><label id="entry-label"><input type="checkbox" id="include-entry"> 출입정보 포함</label></div><div class="share-grid"><button id="share-copy">▣ 텍스트 복사</button><button id="share-sms">▢ 문자로 보내기</button><button id="share-kakao">● 카카오톡 공유</button></div></section><section class="order-card side-card preview-card"><h3>전송 미리보기</h3><pre class="preview-paper" id="preview"></pre></section><section class="order-card side-card security-card"><h3>출입정보 보호</h3><p>비밀번호는 기본적으로 공유 문구에서 제외되며, 출입정보 포함을 선택한 경우에만 전송됩니다.</p></section></aside></div></main></div><aside class="order-list-panel" id="order-list-panel" hidden><button class="o-btn list-close" id="close-list">닫기</button><h2>발주 목록</h2><div id="order-list"></div></aside><div class="toast-v2" id="o-toast"></div>';}
function setup(){load();shell();document.getElementById('o-user').textContent=user().name||user().email||'DAHAM';fillSelects();bind();renderQuoteChips();ensureInsertButton();newOrder();renderList();readRemote().then(renderList);}
function ensureInsertButton(){var editor=document.getElementById('quote-editor'),button=document.createElement('button');button.id='insert-brand-mode';button.className='o-btn quote-insert';button.textContent='선택한 브랜드·방식 본문에 삽입';button.onclick=function(){insertQuote(brand+' '+windowMode);};editor.insertBefore(button,document.getElementById('quote-content'));}
function fillSelects(){document.getElementById('o-site').innerHTML='<option value="">현장 선택</option>'+sites.filter(function(x){return x&&x.id;}).map(function(x){return '<option value="'+esc(x.id)+'">'+esc((x.info&&(x.info.addr||x.info.name))||'현장명 미입력')+'</option>';}).join('');document.getElementById('o-vendor').innerHTML='<option value="">거래처 선택</option>'+contacts.map(function(x){return '<option value="'+esc(x.id)+'">'+esc(x.name||x.company||'거래처')+'</option>';}).join('');}
function currentSite(){return sites.find(function(x){return String(x.id)===val('o-site');});}function currentEstimate(){var s=currentSite();return s&&estimates.find(function(e){return String(e.id)===String(s.estimateId);});}
function updateTrades(){var list=mode==='quote'?(DAHAM_ORDER_DOMAIN.hasWindowTrade(currentEstimate())?['창호·샷시']:[]):DAHAM_ORDER_DOMAIN.generalTrades(currentEstimate());document.getElementById('o-trade').innerHTML=list.length?list.map(function(x){return '<option>'+esc(x)+'</option>';}).join(''):'<option value="">연결 공종 없음</option>';}
function bind(){document.querySelectorAll('[data-mode]').forEach(function(b){b.onclick=function(){switchMode(b.dataset.mode);};});document.getElementById('o-site').onchange=siteChanged;document.getElementById('save-order').onclick=function(){saveOrder(false);};document.getElementById('draft-save').onclick=function(){saveOrder(true);};document.getElementById('open-list').onclick=function(){renderList();document.getElementById('order-list-panel').hidden=false;};document.getElementById('close-list').onclick=function(){document.getElementById('order-list-panel').hidden=true;};document.getElementById('share-copy').onclick=copyShare;document.getElementById('share-sms').onclick=sendSMS;document.getElementById('share-kakao').onclick=sendKakao;document.getElementById('include-entry').onchange=renderPreview;document.querySelectorAll('input,select,textarea').forEach(function(e){e.addEventListener('input',renderPreview);});}
function switchMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(function(b){b.classList.toggle('active',b.dataset.mode===mode);});document.getElementById('general-editor').hidden=mode!=='general';document.getElementById('quote-editor').hidden=mode!=='quote';document.getElementById('entry-label').hidden=mode==='quote';document.getElementById('writer-title').textContent=mode==='quote'?'창호 견적 발주 작성':'일반 발주 작성';updateTrades();renderPreview();}
function siteChanged(){var s=currentSite(),info=s&&s.info||{};set('o-address',info.addr||info.name);set('o-manager',info.manager||user().name);set('o-manager-phone',info.managerPhone||info.tel);updateTrades();renderPreview();}
function renderQuoteChips(){document.getElementById('brand-chips').innerHTML=BRANDS.map(function(x){return '<button data-brand="'+x+'">'+x+'</button>';}).join('');document.querySelectorAll('[data-brand]').forEach(function(b){b.onclick=function(){brand=b.dataset.brand;if(DAHAM_ORDER_DOMAIN.windowModes(brand).indexOf(windowMode)<0)windowMode='제작창';renderQuoteChips();};});var modes=DAHAM_ORDER_DOMAIN.windowModes(brand);document.getElementById('mode-chips').innerHTML=['제작창','완성창'].map(function(x){return '<button data-window-mode="'+x+'" '+(modes.indexOf(x)<0?'disabled':'')+'>'+x+'</button>';}).join('');document.querySelectorAll('[data-window-mode]').forEach(function(b){b.onclick=function(){windowMode=b.dataset.windowMode;renderQuoteChips();};});document.getElementById('window-chips').innerHTML=WINDOW_TYPES.map(function(x){return '<button data-window-type="'+x+'">'+x+'</button>';}).join('');document.querySelectorAll('[data-window-type]').forEach(function(b){b.onclick=function(){insertQuote(b.dataset.windowType);};});document.querySelectorAll('[data-brand]').forEach(function(b){b.classList.toggle('active',b.dataset.brand===brand);});document.querySelectorAll('[data-window-mode]').forEach(function(b){b.classList.toggle('active',b.dataset.windowMode===windowMode);});document.getElementById('quote-selection').textContent=brand+' '+windowMode;}
function insertQuote(type){var e=document.getElementById('quote-content'),insert=(e.value&&!e.value.endsWith('\n')?'\n':'')+type+'\n',start=e.selectionStart||e.value.length;e.value=e.value.slice(0,start)+insert+e.value.slice(start);e.focus();e.selectionStart=e.selectionEnd=start+insert.length;renderPreview();}
function draft(){var s=currentSite(),v=contacts.find(function(x){return String(x.id)===val('o-vendor');});return {type:mode,projId:s?s.id:'',estimateId:s?s.estimateId||'':'',projName:s&&s.info?(s.info.addr||s.info.name||''):'',siteName:s&&s.info?(s.info.addr||s.info.name||''):'',trade:val('o-trade'),supplierId:v?v.id:'',supplierName:v?(v.name||v.company||''):'',address:val('o-address'),detailAddress:val('o-detail-address'),deliveryDate:val('o-delivery'),commonEntryCode:val('o-common'),doorCode:val('o-door'),deliveryLocation:val('o-location'),manager:val('o-manager'),managerPhone:val('o-manager-phone'),subPhone:val('o-sub-phone'),deliveryRequest:val('o-delivery-request'),driverNote:val('o-driver-note'),content:mode==='quote'?val('quote-content'):val('order-content')};}
function persist(){localStorage.setItem(ORDER_KEY,JSON.stringify(records));var token=DAHAM_AUTH.getAccessToken&&DAHAM_AUTH.getAccessToken(),cfg=DAHAM_AUTH.getSupabaseConfig&&DAHAM_AUTH.getSupabaseConfig();if(token&&cfg&&cfg.url)fetch(cfg.url+'/rest/v1/sync_data',{method:'POST',headers:{apikey:cfg.anonKey,Authorization:'Bearer '+token,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key:ORDER_KEY,value:JSON.stringify(records),updated_at:new Date().toISOString()})}).catch(function(){});}
function readRemote(){var token=DAHAM_AUTH.getAccessToken&&DAHAM_AUTH.getAccessToken(),cfg=DAHAM_AUTH.getSupabaseConfig&&DAHAM_AUTH.getSupabaseConfig();if(!token||!cfg||!cfg.url)return Promise.resolve();return fetch(cfg.url+'/rest/v1/sync_data?key=eq.'+encodeURIComponent(ORDER_KEY)+'&select=value',{headers:{apikey:cfg.anonKey,Authorization:'Bearer '+token}}).then(function(r){return r.ok?r.json():[];}).then(function(rows){if(rows&&rows[0]&&rows[0].value){var remote=typeof rows[0].value==='string'?JSON.parse(rows[0].value):rows[0].value;if(Array.isArray(remote)){records=remote;localStorage.setItem(ORDER_KEY,JSON.stringify(records));}}}).catch(function(){});}
function saveOrder(isDraft){var d=draft();if(!d.projId){toast('현장을 선택해주세요');return;}if(!d.content){toast('발주 내용을 입력해주세요');return;}var status=isDraft?'pending':'ordered';if(editingRecord){var next=Object.assign({},editingRecord,d,{status:status,updatedAt:new Date().toISOString()});records=records.map(function(x){return x.id===editingRecord.id?next:x;});editingRecord=next;}else{editingRecord=Object.assign({},d,{id:uid(),status:status,createdAt:new Date().toISOString()});records.push(editingRecord);}persist();renderList();toast(isDraft?'임시저장했습니다':'발주를 저장했습니다');}
function shareText(){var d=draft(),includeEntry=document.getElementById('include-entry').checked;if(includeEntry)return mode==='quote'?DAHAM_ORDER_DOMAIN.quoteShareText(d):DAHAM_ORDER_DOMAIN.generalShareText(d,true);return mode==='quote'?DAHAM_ORDER_DOMAIN.quoteShareText(d):DAHAM_ORDER_DOMAIN.generalShareText(d,false);}
function copyShare(){var t=shareText();if(navigator.clipboard)navigator.clipboard.writeText(t).then(function(){toast('텍스트를 복사했습니다');});else toast('복사를 지원하지 않는 브라우저입니다');}
function sendSMS(){location.href='sms:?&body='+encodeURIComponent(shareText());}
function sendKakao(){var t=shareText();if(navigator.share){navigator.share({title:mode==='quote'?'창호 견적 발주':'일반 발주',text:t}).catch(function(){});return;}copyShare();toast('공유 기능이 없어 텍스트를 복사했습니다');}
function renderPreview(){var e=document.getElementById('preview');if(e)e.textContent=shareText();}
function renderList(){var h=document.getElementById('order-list');if(!h)return;h.innerHTML=records.length?records.slice().reverse().map(function(r){return '<div class="list-row" data-id="'+esc(r.id)+'"><strong>'+esc(r.projName||'현장명 없음')+' · '+esc(r.type==='quote'?'견적 발주':r.trade||r.cat||'일반 발주')+'</strong><span>'+esc(r.supplierName||'거래처 미지정')+' / '+esc(r.deliveryDate||'납기 미정')+'</span></div>';}).join(''):'<p class="muted">저장된 발주가 없습니다.</p>';h.querySelectorAll('[data-id]').forEach(function(x){x.onclick=function(){edit(x.dataset.id);};});}
function legacyContent(r){return (r.items||[]).map(function(item){return [item.name||item.item||'',item.spec||'',item.qty?(item.qty+(item.unit||'')):'',item.note||''].filter(Boolean).join(' / ');}).filter(Boolean).join('\n');}
function edit(id){var r=records.find(function(x){return x.id===id;});if(!r)return;editingRecord=r;switchMode(r.type||'general');set('o-site',r.projId);siteChanged();set('o-trade',r.trade||r.cat);set('o-vendor',r.supplierId);var map={address:'o-address',detailAddress:'o-detail-address',deliveryDate:'o-delivery',commonEntryCode:'o-common',doorCode:'o-door',deliveryLocation:'o-location',manager:'o-manager',managerPhone:'o-manager-phone',subPhone:'o-sub-phone',deliveryRequest:'o-delivery-request',driverNote:'o-driver-note'};Object.keys(map).forEach(function(k){set(map[k],r[k]);});set(r.type==='quote'?'quote-content':'order-content',r.content||legacyContent(r));document.getElementById('order-list-panel').hidden=true;renderPreview();}
function newOrder(){editingRecord=null;['o-site','o-address','o-detail-address','o-delivery','o-common','o-door','o-location','o-manager-phone','o-sub-phone','o-delivery-request','o-driver-note','order-content','quote-content'].forEach(function(id){set(id,'');});set('o-manager',user().name||'');switchMode('general');}
if(window.DAHAM_AUTH&&DAHAM_AUTH.ready)DAHAM_AUTH.ready.then(function(ok){if(ok)setup();});else window.addEventListener('DOMContentLoaded',setup);
})();
