(function(){
'use strict';
var ORDER_KEY='daham_order_v1',SCHED_KEY='daham_schedule_v1',EST_KEY='daham_detail_v2',CONTACT_KEY='daham_contacts_v1';
var CATEGORIES=['타일·도기·욕실악세사리','조명·스위치·콘센트','도배지','목자재','기타'];
var WOOD=['석고보드','삼부합판','MDF','다루끼','기타'];
var records=[],sites=[],estimates=[],contacts=[],category=CATEGORIES[0],editingRecord=null,rows=[],attachments=[];
function parse(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d));}catch(e){return d;}}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');}
function val(id){var e=document.getElementById(id);return e?e.value.trim():'';}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7);}
function today(){return new Date().toISOString().slice(0,10);}
function toast(s){var e=document.getElementById('o-toast');e.textContent=s;e.classList.add('show');setTimeout(function(){e.classList.remove('show');},2200);}
function user(){try{return DAHAM_AUTH.currentUser()||{};}catch(e){return {};}}
function load(){records=parse(ORDER_KEY,[]);sites=parse(SCHED_KEY,[]);estimates=parse(EST_KEY,[]);contacts=parse(CONTACT_KEY,[]);}
function persist(){localStorage.setItem(ORDER_KEY,JSON.stringify(records));if(window.DAHAM_WORKFLOW&&DAHAM_WORKFLOW.syncOrders)DAHAM_WORKFLOW.syncOrders(records);syncRemote();}
function syncRemote(){var token=window.DAHAM_AUTH&&DAHAM_AUTH.getAccessToken&&DAHAM_AUTH.getAccessToken(),cfg=window.DAHAM_AUTH&&DAHAM_AUTH.getSupabaseConfig&&DAHAM_AUTH.getSupabaseConfig();if(!token||!cfg||!cfg.url)return;fetch(cfg.url+'/rest/v1/sync_data',{method:'POST',headers:{apikey:cfg.anonKey,Authorization:'Bearer '+token,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key:ORDER_KEY,value:JSON.stringify(records),updated_at:new Date().toISOString()})}).then(function(r){if(!r.ok)throw Error('sync');}).catch(function(){toast('로컬 저장 완료 · 동기화 확인 필요');});}
function readRemote(){var token=window.DAHAM_AUTH&&DAHAM_AUTH.getAccessToken&&DAHAM_AUTH.getAccessToken(),cfg=window.DAHAM_AUTH&&DAHAM_AUTH.getSupabaseConfig&&DAHAM_AUTH.getSupabaseConfig();if(!token||!cfg||!cfg.url)return Promise.resolve();return fetch(cfg.url+'/rest/v1/sync_data?key=eq.'+ORDER_KEY+'&select=value,updated_at',{headers:{apikey:cfg.anonKey,Authorization:'Bearer '+token}}).then(function(r){return r.ok?r.json():[];}).then(function(x){if(x[0]&&x[0].value){var remote=typeof x[0].value==='string'?JSON.parse(x[0].value):x[0].value;if(Array.isArray(remote)){records=remote;localStorage.setItem(ORDER_KEY,JSON.stringify(records));}}}).catch(function(){});}
function shell(){document.body.className='order-v2';document.body.innerHTML='<div class="order-shell"><aside class="order-side"><div class="order-logo">DAHAM<small>INTERIOR RENOVATION</small></div><nav class="order-nav"><a href="index.html">⌂ <span>대시보드</span></a><a href="estimate.html">▤ <span>견적 관리</span></a><a href="order.html" class="active">▣ <span>발주 작성</span></a><a href="contacts.html">♙ <span>업체 관리</span></a><a href="schedule.html">□ <span>일정 관리</span></a><a href="employees.html">⚙ <span>설정</span></a></nav><div class="order-user"><strong id="o-user">DAHAM</strong><span id="o-role">사용자</span></div></aside><main class="order-main"><header class="order-head"><h1>발주 작성</h1><div class="head-actions"><button class="o-btn" id="open-list">발주 목록</button><button class="o-btn" id="draft-save">임시 저장</button><button class="o-btn primary" id="save-order">발주 저장 및 목록으로 →</button></div></header><div class="order-work"><section><div class="order-card"><div class="category-tabs" id="cat-tabs"></div><div class="basic"><div class="form-grid">'+fields()+'</div></div></div><div class="order-card items-card"><div class="card-title">품목 리스트</div><div id="preset-bar" class="preset-bar"></div><div class="items-scroll"><div class="items-head"><div>품목명 *</div><div>규격·옵션</div><div>수량 *</div><div>단위 *</div><div>납기·비고</div><div>삭제</div></div><div id="item-rows"></div></div><div class="item-actions"><button class="o-btn" id="add-row">＋ 품목 추가</button></div></div></section><aside class="right-stack"><section class="order-card side-card wallpaper-card"><h3>도배지 추천 <small class="muted">(현재 유효 견적 기준)</small></h3><div id="wallpaper-box"></div></section><section class="order-card side-card share-card"><div class="share-head"><h3>공유 및 출력</h3><label><input type="checkbox" id="include-entry"> 출입정보 포함</label></div><div class="share-grid"><button id="share-sms">▢ 문자 보내기</button><button id="share-kakao">● 카카오톡 공유</button><button id="share-copy">▣ 복사</button><button id="share-print">▤ 인쇄 / PDF</button></div></section><section class="order-card side-card preview-card"><h3>발주서 미리보기 <small class="muted">(거래처 전송용)</small></h3><div class="preview-paper" id="preview"></div></section></aside></div></main></div><aside class="order-list-panel" id="order-list-panel" hidden><button class="o-btn list-close" id="close-list">닫기</button><h2>발주 목록</h2><div id="order-list"></div></aside><div class="toast-v2" id="o-toast"></div>';}
function fields(){return '<div class="field wide"><label>현장 *</label><select id="o-site"></select></div><div class="field wide"><label>현장주소</label><input id="o-address" readonly></div><div class="field wide"><label>거래처</label><select id="o-vendor"></select></div><div class="field"><label>발주일 *</label><input id="o-date" type="date"></div><div class="field"><label>납기요청일</label><input id="o-delivery" type="date"></div><div class="field"><label>시공일정</label><input id="o-schedule" placeholder="일정에서 자동 제안 · 직접 수정 가능"></div><div class="field"><label>담당자</label><input id="o-manager"></div><div class="field"><label>공동현관 비밀번호</label><input id="o-common"></div><div class="field"><label>현관 비밀번호</label><input id="o-door"></div><div class="field full"><label>메모</label><textarea id="o-memo" placeholder="배송 및 현장 주의사항"></textarea></div><div class="field full"><label>첨부파일</label><div class="file-box"><span id="file-label">파일을 선택하세요 (파일명 정보 저장)</span><label class="o-btn">파일 선택<input id="o-files" type="file" multiple hidden></label></div></div>';}
function setup(){load();shell();var u=user();document.getElementById('o-user').textContent=u.name||u.email||'DAHAM';document.getElementById('o-role').textContent=u.role==='owner'?'대표':u.role==='admin'?'관리자':'직원';renderTabs();fillSelects();bind();newOrder();readRemote().then(function(){renderList();});}
function renderTabs(){document.getElementById('cat-tabs').innerHTML=CATEGORIES.map(function(c){return '<button data-cat="'+c+'" class="'+(c===category?'active':'')+'">'+c+'</button>';}).join('');document.querySelectorAll('[data-cat]').forEach(function(b){b.onclick=function(){category=b.dataset.cat;renderTabs();renderPresets();updateWallpaper();renderPreview();};});}
function fillSelects(){var s=document.getElementById('o-site');s.innerHTML='<option value="">현장 선택</option>'+sites.filter(function(x){return x.estimateId||x.sourceType==='contract';}).map(function(x){return '<option value="'+esc(x.id)+'">'+esc((x.info&&x.info.name)||'현장명 미입력')+'</option>';}).join('');var v=document.getElementById('o-vendor');v.innerHTML='<option value="">거래처 선택</option>'+contacts.map(function(x){return '<option value="'+esc(x.id)+'">'+esc(x.name||x.company||'거래처')+'</option>';}).join('');}
function bind(){document.getElementById('o-site').onchange=siteChanged;document.getElementById('add-row').onclick=function(){addRow({});};document.getElementById('save-order').onclick=function(){saveOrder(false);};document.getElementById('draft-save').onclick=function(){saveOrder(true);};document.getElementById('open-list').onclick=openList;document.getElementById('close-list').onclick=function(){document.getElementById('order-list-panel').hidden=true;};document.getElementById('o-files').onchange=function(e){attachments=[].map.call(e.target.files,function(f){return {name:f.name,size:f.size,type:f.type};});document.getElementById('file-label').textContent=attachments.length?attachments.map(function(x){return x.name;}).join(', '):'파일을 선택하세요 (파일명 정보 저장)';};['o-address','o-date','o-delivery','o-schedule','o-manager','o-common','o-door','o-memo','o-vendor'].forEach(function(id){document.getElementById(id).addEventListener('input',renderPreview);});document.getElementById('share-copy').onclick=copyShare;document.getElementById('share-sms').onclick=sendSMS;document.getElementById('share-kakao').onclick=sendKakao;document.getElementById('share-print').onclick=function(){window.print();};}
function newOrder(){editingRecord=null;category=CATEGORIES[0];renderTabs();['o-site','o-address','o-vendor','o-delivery','o-schedule','o-common','o-door','o-memo'].forEach(function(id){document.getElementById(id).value='';});document.getElementById('o-date').value=today();document.getElementById('o-manager').value=user().name||'';attachments=[];rows=[];document.getElementById('item-rows').innerHTML='';addRow({});renderPresets();updateWallpaper();renderPreview();}
function siteChanged(){var site=sites.find(function(x){return x.id===val('o-site');});document.getElementById('o-address').value=site&&site.info?(site.info.addr||''):'';if(site){var tasks=site.tasks||[],starts=tasks.map(function(t){return t.start;}).filter(Boolean).sort(),ends=tasks.map(function(t){return t.end||t.start;}).filter(Boolean).sort();document.getElementById('o-schedule').value=starts.length?(starts[0]+' ~ '+ends[ends.length-1]):((site.info&&site.info.start&&site.info.end)?site.info.start+' ~ '+site.info.end:'');}updateWallpaper();renderPreview();}
function addRow(item){var old=item||{},id=uid();rows.push({id:id,raw:old});var host=document.getElementById('item-rows'),line=document.createElement('div');line.className='item-line';line.dataset.row=id;line.innerHTML='<input data-k="name" placeholder="직접 입력" value="'+esc(old.name||'')+'"><input data-k="spec" placeholder="두께·규격·옵션" value="'+esc(old.spec||old.option||'')+'"><input data-k="qty" inputmode="decimal" value="'+esc(old.qty||'')+'"><select data-k="unit">'+['개','장','롤','세트','박스','포','식','m','㎡','기타'].map(function(u){return '<option'+(u===(old.unit||'개')?' selected':'')+'>'+u+'</option>';}).join('')+'</select><input data-k="note" placeholder="납기·비고" value="'+esc(old.note||'')+'"><button class="delete-row" title="행 삭제">⌫</button>';host.appendChild(line);line.querySelectorAll('input,select').forEach(function(e){e.oninput=renderPreview;});line.querySelector('.delete-row').onclick=function(){rows=rows.filter(function(r){return r.id!==id;});line.remove();renderPreview();};}
function renderPresets(){var b=document.getElementById('preset-bar');if(category==='목자재'){b.innerHTML='<span>빠른 품목</span>'+WOOD.map(function(x){return '<button class="preset">'+x+'</button>';}).join('');b.querySelectorAll('button').forEach(function(x){x.onclick=function(){addRow({name:x.textContent,unit:'장'});};});}else b.innerHTML='<span>모든 카테고리에서 품목명을 직접 입력할 수 있습니다.</span>';}
function getRows(){return [].map.call(document.querySelectorAll('.item-line'),function(line,i){var oldItem=(rows.find(function(r){return r.id===line.dataset.row;})||{}).raw||{},next={};line.querySelectorAll('[data-k]').forEach(function(x){next[x.dataset.k]=x.value.trim();});return Object.assign({},oldItem,next);}).filter(function(x){return x.name;});}
function currentSite(){return sites.find(function(x){return x.id===val('o-site');});}
function wallpaperSource(){var site=currentSite();if(!site||!site.estimateId)return null;var estimate=estimates.find(function(estimate){return estimate.id===site.estimateId;});if(!estimate)return null;var list=estimate.selectedMaterials||[];var found=list.filter(function(m){return m.sec==='도배'&&Number(m.qty)>0;});if(!found.length)return null;return {estimate:estimate,items:found,qty:found.reduce(function(n,m){return n+Number(m.qty||0);},0)};}
function updateWallpaper(){var box=document.getElementById('wallpaper-box'),src=wallpaperSource();if(category!=='도배지'){box.innerHTML='<p class="wallpaper-note">도배지 탭에서 연결된 유효 견적의 실제 도배 수량을 확인할 수 있습니다.</p>';return;}if(!src){box.innerHTML='<p class="wallpaper-note">연결된 현재 유효 견적에 재사용 가능한 도배 수량이 없습니다. 도배 품목은 자동 생성하지 않습니다.</p>';return;}box.innerHTML='<div class="wallpaper-row"><span>견적 도배 수량</span><strong>'+esc(src.qty)+' <small>롤</small></strong></div><p class="wallpaper-note">견적에 저장된 실제 수량만 사용했습니다. 별도 여유분 계산식은 적용하지 않았으며 제안 수량은 수정할 수 있습니다.</p><div class="wallpaper-edit"><input id="wallpaper-qty" type="number" value="'+esc(src.qty)+'"><span>롤</span><button class="o-btn" id="apply-wallpaper">품목 적용</button></div>';document.getElementById('apply-wallpaper').onclick=function(){addRow({name:src.items.map(function(x){return x.sub+(x.det?' '+x.det:'');}).join(', '),spec:'견적 기준',qty:document.getElementById('wallpaper-qty').value,unit:'롤'});};}
function draft(){var site=currentSite(),vendor=contacts.find(function(x){return x.id===val('o-vendor');});return {projId:site?site.id:'',estimateId:site?site.estimateId||'':'',projName:site&&site.info?(site.info.name||site.info.addr||''):'',address:val('o-address'),cat:category,supplierId:vendor?vendor.id:'',supplierName:vendor?(vendor.name||vendor.company||''):'',supplierTel:vendor?(vendor.tel||''):'',orderDate:val('o-date'),deliveryDate:val('o-delivery'),constructionSchedule:val('o-schedule'),manager:val('o-manager'),commonEntryCode:val('o-common'),doorCode:val('o-door'),memo:val('o-memo'),attachments:attachments,items:getRows()};}
function saveOrder(isDraft){var d=draft();if(!d.projId){toast('현장을 선택해주세요');return;}if(!d.items.length){toast('품목을 한 개 이상 입력해주세요');return;}if(editingRecord){var next=Object.assign({},editingRecord,d,{status:isDraft?'pending':(editingRecord.status||'ordered'),updatedAt:new Date().toISOString()});records=records.map(function(x){return x.id===editingRecord.id?next:x;});editingRecord=next;}else{editingRecord=Object.assign({},d,{id:uid(),status:isDraft?'pending':'ordered',createdAt:new Date().toISOString()});records.push(editingRecord);}persist();renderList();renderPreview();toast(isDraft?'임시 저장했습니다':'발주를 저장했습니다');if(!isDraft)openList();}
function openList(){renderList();document.getElementById('order-list-panel').hidden=false;}
function renderList(){var h=document.getElementById('order-list');if(!h)return;h.innerHTML=records.length?records.slice().reverse().map(function(r){return '<div class="list-row" data-id="'+esc(r.id)+'"><strong>'+esc(r.projName||'현장명 없음')+' · '+esc(r.cat||'기타')+'</strong><span>'+esc(r.supplierName||'거래처 미지정')+' / '+esc(r.deliveryDate||'납기 미정')+'</span></div>';}).join(''):'<p class="muted">저장된 발주가 없습니다.</p>';h.querySelectorAll('[data-id]').forEach(function(x){x.onclick=function(){edit(x.dataset.id);};});}
function edit(id){var r=records.find(function(x){return x.id===id;});if(!r)return;editingRecord=r;category=CATEGORIES.indexOf(r.cat)>=0?r.cat:'기타';renderTabs();document.getElementById('o-site').value=r.projId||'';document.getElementById('o-address').value=r.address||'';document.getElementById('o-vendor').value=r.supplierId||'';document.getElementById('o-date').value=r.orderDate||r.createdAt&&r.createdAt.slice(0,10)||today();document.getElementById('o-delivery').value=r.deliveryDate||'';document.getElementById('o-schedule').value=r.constructionSchedule||'';document.getElementById('o-manager').value=r.manager||'';document.getElementById('o-common').value=r.commonEntryCode||'';document.getElementById('o-door').value=r.doorCode||'';document.getElementById('o-memo').value=r.memo||'';attachments=r.attachments||[];rows=[];document.getElementById('item-rows').innerHTML='';(r.items||[]).forEach(addRow);if(!r.items||!r.items.length)addRow({});renderPresets();updateWallpaper();renderPreview();document.getElementById('order-list-panel').hidden=true;}
function shareText(){var d=draft(),includeEntry=document.getElementById('include-entry').checked,lines=['[DAHAM 발주서]','현장: '+(d.projName||'-'),'주소: '+(d.address||'-'),'시공일정: '+(d.constructionSchedule||'-'),'납기일: '+(d.deliveryDate||'-'),''];d.items.forEach(function(x){lines.push('· '+x.name+' / '+(x.spec||'-')+' / '+(x.qty||'-')+(x.unit||'')+(x.note?' / '+x.note:''));});if(d.memo)lines.push('', '메모: '+d.memo);if(includeEntry){if(d.commonEntryCode)lines.push('공동현관: '+d.commonEntryCode);if(d.doorCode)lines.push('현관: '+d.doorCode);}return lines.join('\n');}
function copyShare(){var t=shareText();if(navigator.clipboard)navigator.clipboard.writeText(t).then(function(){toast('발주 내용을 복사했습니다');});else{var a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();toast('발주 내용을 복사했습니다');}}
function sendSMS(){if(!/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent)){copyShare();toast('PC에서는 문자 내용을 복사했습니다');return;}location.href='sms:?&body='+encodeURIComponent(shareText());}
function sendKakao(){if(window.Kakao&&Kakao.Share&&Kakao.isInitialized&&Kakao.isInitialized()){Kakao.Share.sendDefault({objectType:'text',text:shareText(),link:{mobileWebUrl:location.href,webUrl:location.href}});return;}copyShare();toast('Kakao JavaScript 키가 없어 내용을 복사했습니다');}
function renderPreview(){var d=draft(),items=d.items||[];document.getElementById('preview').innerHTML='<h2>발 주 서</h2><div class="preview-meta"><b>현장명</b><span>'+esc(d.projName||'-')+'</span><b>현장주소</b><span>'+esc(d.address||'-')+'</span><b>거래처</b><span>'+esc(d.supplierName||'-')+'</span><b>발주일</b><span>'+esc(d.orderDate||'-')+'</span><b>납기요청</b><span>'+esc(d.deliveryDate||'-')+'</span><b>시공일정</b><span>'+esc(d.constructionSchedule||'-')+'</span><b>담당자</b><span>'+esc(d.manager||'-')+'</span></div><table class="preview-table"><thead><tr><th>품목명</th><th>규격/옵션</th><th>수량</th><th>단위</th></tr></thead><tbody>'+items.map(function(x){return '<tr><td>'+esc(x.name)+'</td><td>'+esc(x.spec||'-')+'</td><td>'+esc(x.qty||'-')+'</td><td>'+esc(x.unit||'-')+'</td></tr>';}).join('')+'</tbody></table>'+(d.memo?'<p style="margin-top:12px">'+esc(d.memo)+'</p>':'');}
if(window.DAHAM_AUTH&&DAHAM_AUTH.ready)DAHAM_AUTH.ready.then(function(ok){if(ok)setup();});else window.addEventListener('DOMContentLoaded',setup);
})();

