(function(){
'use strict';
var SCHED_KEY='daham_schedule_v1',EST_KEY='daham_detail_v2',SPEC_KEY='daham_spec_v1',SPEC_TS_KEY=SPEC_KEY+'_ts';
var schedules=[],estimates=[],savedSpecs=[],currentModel=null,currentSchedule=null,currentEstimate=null,openTradeId='',reorderMode=false,client=null;
var $=function(id){return document.getElementById(id);};
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch(e){return fallback;}}
function dateOnly(){return new Date().toISOString().slice(0,10);}function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}
function formatTime(value){if(!value)return '저장 내역 없음';var d=new Date(value);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');}
function toast(message){var el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(function(){el.classList.remove('show');},1800);}
function initClient(){if(client)return client;try{var auth=window.DAHAM_SPEC_AUTH||{},c=auth.config||DAHAM_AUTH.getSupabaseConfig(),token=auth.token||DAHAM_AUTH.getAccessToken();client=window.supabase.createClient(c.url,c.key,{global:{headers:token?{Authorization:'Bearer '+token}:{}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});}catch(e){client=null;}return client;}
async function pullCloud(){var sb=initClient();if(!sb)return;try{var r=await sb.from('sync_data').select('key,value,updated_at').in('key',[SCHED_KEY,EST_KEY,SPEC_KEY]);if(r.error)throw r.error;(r.data||[]).forEach(function(row){var ts=localStorage.getItem(row.key+'_ts')||'';if(row.updated_at>ts&&row.value){localStorage.setItem(row.key,row.value);localStorage.setItem(row.key+'_ts',row.updated_at);}});}catch(e){console.warn('시방서 데이터 동기화:',e.message||e);}}
function loadData(){schedules=read(SCHED_KEY,[]);estimates=read(EST_KEY,[]);savedSpecs=read(SPEC_KEY,[]);}
function populateSites(){$('site-select').innerHTML='<option value="">현장을 선택하세요</option>'+schedules.filter(function(s){return s&&s.id;}).map(function(s){var i=s.info||{};return '<option value="'+esc(s.id)+'">▦ '+esc(i.addr||i.name||'현장명 미입력')+'</option>';}).join('');}
function savedForSite(id){return savedSpecs.find(function(s){return String(s.siteId||s.schedId)===String(id);});}
function selectSite(id){currentSchedule=schedules.find(function(s){return String(s.id)===String(id);})||null;currentEstimate=null;currentModel=null;openTradeId='';if(currentSchedule){currentEstimate=estimates.find(function(e){return String(e.id)===String(currentSchedule.estimateId);})||null;currentModel=DAHAM_SPEC_DOMAIN.mergeSaved(DAHAM_SPEC_DOMAIN.createModel(currentSchedule,currentEstimate,new Date().toISOString()),savedForSite(currentSchedule.id));if(currentModel.trades.length)openTradeId=currentModel.trades[0].id;}renderAll();}
function markDirty(){if(!currentModel)return;$('save-state').textContent='저장 필요';$('save-state').classList.add('pending');$('draft-indicator').textContent='◷ 변경사항 있음';renderProgress();renderPreview();}
function statusLabel(s){return s==='completed'?'작성 완료':s==='in-progress'?'작성 중':'미작성';}
function tradeTemplate(t,index){var status=DAHAM_SPEC_DOMAIN.getTradeStatus(t),open=t.id===openTradeId;
var contents=(t.contents||[]).map(function(v,i){return '<div class="content-row"><input class="content-input" data-field="content" data-index="'+i+'" value="'+esc(v)+'" placeholder="시공 내용을 입력하세요"><button class="mini-button danger" data-action="delete-content" data-index="'+i+'">삭제</button></div>';}).join('');
var mats=(t.materials||[]).map(function(m,i){return '<tr data-material-index="'+i+'"><td><input data-material="category" value="'+esc(m.category)+'"></td><td><input data-material="brand" value="'+esc(m.brand)+'"></td><td><input data-material="product" value="'+esc(m.product)+'"></td><td><input data-material="spec" value="'+esc(m.spec)+'"></td><td><input data-material="finish" value="'+esc(m.finish)+'"></td><td><input data-material="note" value="'+esc(m.note)+'"></td><td class="row-delete"><button class="mini-button danger" data-action="delete-material" data-index="'+i+'">×</button></td></tr>';}).join('');
return '<article class="trade-card '+(open?'open':'')+'" data-trade-id="'+esc(t.id)+'"><header class="trade-head" data-action="toggle-trade"><span class="trade-number">'+String(index+1).padStart(2,'0')+'</span><strong class="trade-name">'+esc(t.name)+'</strong><span class="status-badge status-'+status+'">'+statusLabel(status)+'</span><span class="trade-spacer"></span><span class="trade-toggle">⌄</span><span class="move-controls"><button class="mini-button" data-action="move-trade" data-direction="-1">↑</button><button class="mini-button" data-action="move-trade" data-direction="1">↓</button></span><button class="btn" data-action="toggle-trade">✎ 편집</button><button class="btn delete-btn" data-action="delete-trade">♲ 삭제</button></header><div class="trade-body"><div class="edit-grid"><div class="field-block"><label>시공범위</label><textarea class="editable-input" data-field="scope" rows="3" placeholder="시공 범위를 입력하세요">'+esc(t.scope)+'</textarea></div><div class="field-block"><label>시공내용</label><div class="content-list">'+contents+'</div><button class="mini-button add-content" data-action="add-content">＋ 시공내용 추가</button></div></div><div class="material-block"><div class="material-head"><strong>사용 자재</strong><button class="mini-button" data-action="add-material">＋ 자재 추가</button></div><div class="material-table-wrap"><table class="material-table"><thead><tr><th>구분</th><th>브랜드</th><th>제품명 / 모델명</th><th>규격</th><th>색상 / 마감</th><th>비고</th><th>삭제</th></tr></thead><tbody>'+mats+'</tbody></table></div></div></div></article>';}
function tradeTemplateFree(t,index){var status=DAHAM_SPEC_DOMAIN.getTradeStatus(t),open=t.id===openTradeId;var contents=(t.contents||[]).map(function(v,i){return '<div class="content-row"><input class="content-input" data-field="content" data-index="'+i+'" value="'+esc(v)+'" placeholder="시공 내용을 입력하세요"><button class="mini-button danger" data-action="delete-content" data-index="'+i+'">삭제</button></div>';}).join('');return '<article class="trade-card '+(open?'open':'')+'" data-trade-id="'+esc(t.id)+'"><header class="trade-head" data-action="toggle-trade"><span class="trade-number">'+String(index+1).padStart(2,'0')+'</span><strong class="trade-name">'+esc(t.name)+'</strong><span class="status-badge status-'+status+'">'+statusLabel(status)+'</span><span class="trade-spacer"></span><span class="trade-toggle">⌄</span><span class="move-controls"><button class="mini-button" data-action="move-trade" data-direction="-1">↑</button><button class="mini-button" data-action="move-trade" data-direction="1">↓</button></span><button class="btn" data-action="toggle-trade">✎ 편집</button><button class="btn delete-btn" data-action="delete-trade">♲ 삭제</button></header><div class="trade-body"><div class="edit-grid"><div class="field-block"><label>시공범위</label><textarea class="editable-input" data-field="scope" rows="3" placeholder="시공 범위를 입력하세요">'+esc(t.scope)+'</textarea></div><div class="field-block"><label>시공내용</label><div class="content-list">'+contents+'</div><button class="mini-button add-content" data-action="add-content">＋ 시공내용 추가</button></div></div><div class="material-block material-free-block"><div class="material-head"><strong>사용 자재</strong></div><p class="material-free-help">브랜드, 제품명, 규격, 색상, 마감 등 필요한 내용을 자유롭게 입력하세요.</p><textarea class="material-free-input" data-field="materialText" placeholder="예: KCC 친환경 합판 12T / 내추럴">'+esc(t.materialText)+'</textarea><small>줄바꿈으로 항목 구분</small></div></div></article>';}
function tradePeriod(t){if(!t.scheduleStart&&!t.scheduleEnd)return '';return t.scheduleStart+(t.scheduleEnd&&t.scheduleEnd!==t.scheduleStart?' – '+t.scheduleEnd:'');}
function tradeTemplateScheduled(t,index){var html=tradeTemplateFree(t,index),period=tradePeriod(t);if(!period)return html;html=html.replace('<span class="trade-spacer">','<span class="trade-period">▣ '+esc(period)+'</span><span class="trade-spacer">');var schedule='<div class="trade-schedule-row"><div><small>작업 시작</small><strong>'+esc(t.scheduleStart)+'</strong></div><div><small>작업 종료</small><strong>'+esc(t.scheduleEnd||t.scheduleStart)+'</strong></div><span>일정 관리에서 연동</span></div>';return html.replace('<div class="trade-body">','<div class="trade-body">'+schedule);}
function renderEditor(){var e=$('empty-editor'),list=$('trade-list');if(!currentModel){e.hidden=false;list.innerHTML='';return;}e.hidden=true;list.classList.toggle('reorder-mode',reorderMode);list.innerHTML=currentModel.trades.map(tradeTemplateScheduled).join('');}
function renderInfo(){var n=currentModel&&(currentModel.estimateNo||currentModel.estimateId);$('estimate-link').textContent=n?'견적서 #'+n:'연결 견적 없음';$('written-date').textContent=currentModel?(currentModel.createdAt||'').slice(0,10):dateOnly();$('spec-version').textContent='v'+(currentModel&&currentModel.version||1);var saved=currentModel&&currentModel.savedAt;$('last-saved').textContent=formatTime(saved);$('save-state').textContent=saved?'저장 완료':'미저장';$('save-state').classList.toggle('pending',!saved);$('draft-indicator').textContent=saved?'✓ '+formatTime(saved):'◷ 저장 내역 없음';$('estimate-view').href=currentEstimate?'estimate.html?project='+encodeURIComponent(currentEstimate.id):'estimate.html';}
function renderProgress(){var p=DAHAM_SPEC_DOMAIN.getProgress(currentModel?currentModel.trades:[]);$('progress-bar').style.width=p.percent+'%';$('progress-text').textContent=p.completed+' / '+p.total+' 공종 작성 완료 ('+p.percent+'%)';}
function section(title,body){return body?'<section class="preview-section"><h3>'+title+'</h3>'+body+'</section>':'';}
function renderDocument(model){if(!model)return '<div class="preview-placeholder"><strong>고객 미리보기</strong><span>현장을 선택하면 문서가 표시됩니다.</span></div>';var d=DAHAM_SPEC_DOMAIN.toCustomerDocument(model),b=d.basicInfo||{},rows=[];[['현장명',b.siteName],['현장 주소',b.address],['고객명',b.clientName],['연락처',b.phone],['연결 견적',b.estimateNo],['착공일',b.start],['준공일',b.end]].forEach(function(r){if(r[1])rows.push('<tr><th>'+r[0]+'</th><td>'+esc(r[1])+'</td></tr>');});var scopes=(d.scopes||[]).map(function(s){return '<li><strong>'+esc(s.name)+'</strong> · '+esc(s.scope)+'</li>';}).join('');var mats=(d.materials||[]).map(function(m){return '<tr><td>'+esc(m.trade)+'</td><td>'+esc(m.category)+'</td><td>'+esc(m.brand)+'</td><td>'+esc(m.product)+'</td><td>'+esc(m.spec)+'</td><td>'+esc(m.finish)+'</td><td>'+esc(m.note)+'</td></tr>';}).join('');var trades=(d.trades||[]).map(function(t){return '<tr><th>'+esc(t.name)+'</th><td>'+((t.contents||[]).map(function(c){return '<div>• '+esc(c)+'</div>';}).join(''))+'</td></tr>';}).join('');var notes=d.notes?'<ul class="doc-note-list">'+d.notes.split('\n').filter(Boolean).map(function(n){return '<li>'+esc(n)+'</li>';}).join('')+'</ul>':'';return '<div class="doc-brand-row"><span class="doc-brand">DAHAM INTERIOR</span></div><h2 class="doc-title">공사 시방서</h2><p class="doc-intro">아래와 같이 인테리어 공사에 대한 범위, 자재 및 시공 내용을 안내드립니다.</p>'+section('1. 공사 기본정보',rows.length?'<table class="doc-info">'+rows.join('')+'</table>':'')+section('2. 공사 범위',scopes?'<ul class="doc-scope-list">'+scopes+'</ul>':'')+section('3. 자재 및 마감',mats?'<table class="doc-materials"><thead><tr><th>공종</th><th>구분</th><th>브랜드</th><th>제품</th><th>규격</th><th>마감</th><th>비고</th></tr></thead><tbody>'+mats+'</tbody></table>':'')+section('4. 공종별 시공 내용',trades?'<table class="doc-trades"><tbody>'+trades+'</tbody></table>':'')+section('5. 제외/유의사항',notes)+'<footer class="doc-footer-note">위 내용으로 공사를 진행하며, 변경 사항은 사전에 협의드립니다.</footer><div class="doc-ornament">⌒◡⌒</div>';}
function modernSection(number,title,body){return body?'<section class="preview-section"><h3><span class="doc-section-number">'+number+'</span>'+title+'</h3>'+body+'</section>':'';}
function materialText(m){return [m.brand,m.product,m.spec,m.finish,m.note].filter(Boolean).map(esc).join(' · ');}
function renderModernDocument(model){
if(!model)return '<div class="preview-placeholder"><strong>고객 미리보기</strong><span>현장을 선택하면 문서가 표시됩니다.</span></div>';
var d=DAHAM_SPEC_DOMAIN.toCustomerDocument(model),b=d.basicInfo||{},info=[];
[['현장명',b.siteName],['현장 주소',b.address],['고객명',b.clientName],['연락처',b.phone],['연결 견적',b.estimateNo],['착공일',b.start],['준공일',b.end]].forEach(function(r){if(r[1])info.push('<div class="doc-info-item"><strong>'+r[0]+'</strong><span>'+esc(r[1])+'</span></div>');});
var scopes=(d.scopes||[]).map(function(s){return '<li><strong>'+esc(s.name)+'</strong><span>'+esc(s.scope)+'</span></li>';}).join('');
var mats=(d.materialSections||[]).map(function(m){return '<div class="doc-material-card doc-material-free"><strong>'+esc(m.trade)+'</strong><span>'+esc(m.text).replace(/\n/g,'<br>')+'</span></div>';}).join('');
var trades=(d.trades||[]).map(function(t){var period=[t.scheduleStart,t.scheduleEnd&&t.scheduleEnd!==t.scheduleStart?t.scheduleEnd:''].filter(Boolean).join(' – ');return '<div class="doc-trade-item"><strong>'+esc(t.name)+'</strong>'+(period?'<time>'+esc(period)+'</time>':'<time></time>')+'<span>'+((t.contents||[]).map(esc).join(' · ')||esc(t.scope))+'</span></div>';}).join('');
var notes=d.notes?'<ul class="doc-note-list">'+d.notes.split('\n').filter(Boolean).map(function(n){return '<li>'+esc(n)+'</li>';}).join('')+'</ul>':'';
var created=(model.createdAt||'').slice(0,10),saved=model.savedAt?formatTime(model.savedAt):'',meta=[created&&'<span><b>작성일</b> '+esc(created)+'</span>',saved&&'<span><b>최근 저장</b> '+esc(saved)+'</span>'].filter(Boolean).join('');
return '<header class="doc-modern-head"><strong>DAHAM</strong><small>INTERIOR &amp; ARCHITECTURE</small></header><h2 class="doc-title">공사 시방서</h2><p class="doc-intro">아래와 같이 인테리어 공사에 대한 범위, 자재 및 시공 내용을 안내드립니다.</p>'+
modernSection('1','공사 기본정보',info.length?'<div class="doc-info-grid">'+info.join('')+'</div>':'')+
modernSection('2','공사 범위',scopes?'<ul class="doc-scope-list">'+scopes+'</ul>':'')+
modernSection('3','자재 및 마감',mats?'<div class="doc-material-grid">'+mats+'</div>':'')+
modernSection('4','공종별 시공 내용',trades?'<div class="doc-trade-grid"><div class="doc-trade-header"><b>공종</b><b>작업 기간</b><b>시공 내용</b></div>'+trades+'</div>':'')+
modernSection('5','제외 및 유의사항',notes)+
'<p class="doc-agreement">위 내용으로 공사를 진행하며, 변경 사항은 사전에 협의드립니다.</p><footer class="doc-modern-footer"><div class="doc-footer-brand"><strong>DAHAM</strong><span>다함 인테리어 주식회사</span><small>구미시 신시로10길 75-2<br>lloo2059ll@gmail.com</small></div><div class="doc-footer-meta"><span><b>문서명</b> 공사 시방서</span><span><b>버전</b> v'+esc(model.version||1)+'</span>'+meta+'</div><div class="doc-approval"><b>고객 확인 및 승인</b><span>/</span></div></footer><div class="doc-page-number">1 / 1</div>';
}
function renderPreview(){var html=renderModernDocument(currentModel);$('customer-preview').innerHTML=html;$('customer-preview-modal').innerHTML=html;}function renderAll(){renderInfo();renderProgress();renderEditor();renderPreview();}
function findTrade(target){var card=target.closest('[data-trade-id]');return card&&currentModel&&currentModel.trades.find(function(t){return t.id===card.dataset.tradeId;});}
function handleAction(e){var a=e.target.closest('[data-action]');if(!a||!currentModel)return;var action=a.dataset.action,t=findTrade(a);if(!t)return;if(action==='toggle-trade'){e.preventDefault();openTradeId=openTradeId===t.id?'':t.id;renderEditor();return;}e.stopPropagation();var i=currentModel.trades.indexOf(t);if(action==='delete-trade'&&confirm('이 공종을 삭제하시겠습니까?')){currentModel.trades.splice(i,1);openTradeId='';markDirty();renderEditor();}if(action==='add-content'){t.contents.push('');openTradeId=t.id;markDirty();renderEditor();}if(action==='delete-content'){t.contents.splice(Number(a.dataset.index),1);markDirty();renderEditor();}if(action==='add-material'){t.materials.push({id:uid('material'),category:'',brand:'',product:'',spec:'',finish:'',note:''});openTradeId=t.id;markDirty();renderEditor();}if(action==='delete-material'){t.materials.splice(Number(a.dataset.index),1);markDirty();renderEditor();}if(action==='move-trade'){var n=i+Number(a.dataset.direction);if(n>=0&&n<currentModel.trades.length){currentModel.trades.splice(i,1);currentModel.trades.splice(n,0,t);markDirty();renderEditor();}}}
function handleInput(e){if(!currentModel)return;var t=findTrade(e.target);if(!t)return;if(e.target.dataset.field==='scope')t.scope=e.target.value;if(e.target.dataset.field==='content')t.contents[Number(e.target.dataset.index)]=e.target.value;if(e.target.dataset.field==='materialText')t.materialText=e.target.value;if(e.target.dataset.material){var row=e.target.closest('[data-material-index]');t.materials[Number(row.dataset.materialIndex)][e.target.dataset.material]=e.target.value;}markDirty();}
async function saveSpec(){if(!currentModel){toast('현장을 먼저 선택해 주세요.');return;}currentModel.savedAt=new Date().toISOString();var stored=JSON.parse(JSON.stringify(currentModel));stored.schedId=currentModel.siteId;var i=savedSpecs.findIndex(function(s){return String(s.siteId||s.schedId)===String(currentModel.siteId);});if(i>=0)savedSpecs[i]=stored;else savedSpecs.push(stored);var value=JSON.stringify(savedSpecs);localStorage.setItem(SPEC_KEY,value);localStorage.setItem(SPEC_TS_KEY,currentModel.savedAt);var sb=initClient();if(sb){try{var r=await sb.from('sync_data').upsert({key:SPEC_KEY,value:value,updated_at:currentModel.savedAt});if(r.error)throw r.error;}catch(e){toast('로컬 저장 완료 · 클라우드 동기화 실패');renderAll();return;}}renderAll();toast('시방서를 저장했습니다.');}
function addTrade(){if(!currentModel){toast('현장을 먼저 선택해 주세요.');return;}$('new-trade-name').value='';$('trade-modal').classList.add('open');$('trade-modal').setAttribute('aria-hidden','false');setTimeout(function(){$('new-trade-name').focus();},0);}function closeTradeModal(){$('trade-modal').classList.remove('open');$('trade-modal').setAttribute('aria-hidden','true');}function confirmTrade(){var name=$('new-trade-name').value.trim();if(!name){toast('공종명을 입력해 주세요.');return;}var t={id:uid('trade'),name:name,scope:'',contents:[],materials:[]};currentModel.trades.push(t);openTradeId=t.id;closeTradeModal();markDirty();renderEditor();}function toggleReorder(){reorderMode=!reorderMode;$('reorder-button').textContent=reorderMode?'✓ 순서 변경 완료':'↕ 공종 순서 변경';renderEditor();}
function openPreview(){renderPreview();$('preview-modal').classList.add('open');$('preview-modal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}function closePreview(){$('preview-modal').classList.remove('open');$('preview-modal').setAttribute('aria-hidden','true');document.body.style.overflow='';}function printPreview(){renderPreview();window.print();}
function bind(){$('site-select').addEventListener('change',function(){selectSite(this.value);});$('trade-list').addEventListener('click',handleAction);$('trade-list').addEventListener('input',handleInput);$('save-button').addEventListener('click',saveSpec);$('add-trade-button').addEventListener('click',addTrade);$('cancel-trade').addEventListener('click',closeTradeModal);$('confirm-trade').addEventListener('click',confirmTrade);$('new-trade-name').addEventListener('keydown',function(e){if(e.key==='Enter')confirmTrade();});$('reorder-button').addEventListener('click',toggleReorder);$('preview-button').addEventListener('click',openPreview);$('close-preview').addEventListener('click',closePreview);$('print-button').addEventListener('click',printPreview);$('refresh-preview').addEventListener('click',function(){renderPreview();toast('미리보기를 업데이트했습니다.');});window.addEventListener('beforeprint',renderPreview);document.addEventListener('keydown',function(e){if(e.key==='Escape'){closePreview();closeTradeModal();}});}
async function init(){await Promise.resolve(DAHAM_AUTH.ready);var u=DAHAM_AUTH.currentUser&&DAHAM_AUTH.currentUser();if(u)$('sidebar-user-name').textContent=u.name||u.email||'DAHAM';await pullCloud();loadData();populateSites();bind();renderAll();var q=new URLSearchParams(location.search).get('site');if(q&&schedules.some(function(s){return String(s.id)===q;})){$('site-select').value=q;selectSite(q);}}
init();
})();
